<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Spider;
use Doctrine\ORM\EntityRepository;

/**
 * SpiderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpiderRepository extends EntityRepository
{
    /**
     * @param $spiderName
     * @param $site
     * @param $siteDomain
     * @return Spider
     */
    public function createSpider($spiderName, $site, $siteDomain)
    {
        $spider = new Spider();
        
        $spider->setName($spiderName);
        $spider->setDomain($siteDomain);
        $spider->setSite($site);
        
        $nowDate = new \DateTime();
        
        $spider->setCreateTime($nowDate);
        $spider->setUpdateTime($nowDate);
        
        $this->getEntityManager()->persist($spider);
        $this->getEntityManager()->flush();
        
        return $spider;
    }
}
